providers = ["php", "node"]

[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql", "nodejs_18"]

[phases.build]
cmds = ["composer install --optimize-autoloader --no-dev"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"